import assert from 'node:assert/strict';
import test from 'node:test';
import {Account,Address,Keypair,Networks,SorobanDataBuilder,StrKey,TransactionBuilder,scValToNative,xdr} from '@stellar/stellar-sdk';
import {SoranOwner,claimSettingsToScVal,claimLabelToScVal,type ClaimSettings} from '../src/index.js';
import {authorizedInvocation} from '../src/native-auth.js';
import {hex,namespaceNode,sc,struct} from '../src/native-codec.js';
const kp=Keypair.random(),G=kp.publicKey(),OTHER=Keypair.random().publicKey(),C=(i:number)=>StrKey.encodeContract(new Uint8Array(32).fill(i)),REG=C(1),RAR=C(2),RES=C(3),TOKEN=C(4);
const settings:ClaimSettings={mode:'public',enabled:true,admission:{type:'open'},feeToken:TOKEN,feeAmount:0n,feeRecipient:G,walletLimit:0n,approvalAllowance:0n,approvalRateLimit:0n,approvalWindowSecs:0n,approvalTtlSecs:0n};
function fixture(opts:{owner?:string;hash?:string;badSignature?:boolean;badReturn?:boolean;resourceFee?:string;maxFee?:bigint}={}){
 let signed=0,sent=0,lastMethod='',lastArgs:xdr.ScVal[]=[],sentTx:any;const instance=new xdr.ScContractInstance({executable:xdr.ContractExecutable.contractExecutableWasm(opts.hash??'ff'.repeat(32)),storage:[]});
 const client=new SoranOwner({registryId:REG,maxNativeFeeStroops:opts.maxFee,signer:{publicKey:()=>G,signTransaction:async(raw,{networkPassphrase})=>{signed++;const tx=TransactionBuilder.fromXDR(raw,networkPassphrase);if(opts.badSignature){const wrong=TransactionBuilder.cloneFrom(tx as any,{networkPassphrase,fee:'999'}).build();wrong.sign(kp);return wrong.toXDR();}tx.sign(kp);return tx.toXDR();}}});
 const result=()=>lastMethod==='configure_claims'||lastMethod==='set_claim_enabled'?struct({settings:claimSettingsToScVal(settings),owner_epoch:sc.u64(1n),policy_version:sc.u64(2n),grant_epoch:sc.u64(3n)}):lastMethod==='issue_reserved'?sc.bytes(new Uint8Array(32).fill(9)):sc.u32(scValToNative(lastArgs[0]).length);
 Object.assign(client,{read:async(_id:string,fn:string)=>{switch(fn){case'registrar_tainted':return false;case'template_hashes':return[new Uint8Array(32).fill(255),new Uint8Array(32)];case'registrar_of':return RAR;case'native_contracts':return[RAR,RES];case'owner_of':return opts.owner??G;case'owner_epoch':return 1n;case'anchors':return[REG,namespaceNode('nova')];case'claim_version':case'initialization_version':return 1;case'native_fee_token':return TOKEN;case'claim_config':return null;default:throw new Error('unexpected ABI method '+fn);}},server:{getContractInstance:async()=>instance,getAccount:async()=>new Account(G,'0'),simulateTransaction:async(tx:any)=>{const call=tx.operations[0].func.invokeContract;lastMethod=call.functionName.toString();lastArgs=call.args;return{_parsed:true,transactionData:new SorobanDataBuilder().setResourceFee(opts.resourceFee??'0'),minResourceFee:opts.resourceFee??'0',result:{auth:[new xdr.SorobanAuthorizationEntry({credentials:xdr.SorobanCredentials.sorobanCredentialsSourceAccount(),rootInvocation:authorizedInvocation({contract:RAR,method:lastMethod,args:lastArgs})})],retval:result()},events:[],latestLedger:1};},sendTransaction:async(tx:any)=>{sentTx=tx;sent++;return{status:'PENDING',hash:hex(tx.hash())};},getTransaction:async()=>({status:'SUCCESS',txHash:hex(sentTx.hash()),envelopeXdr:sentTx.toEnvelope(),ledger:3,returnValue:opts.badReturn?sc.u64(9n):result()})}});
 return{client,stats:()=>({signed,sent,lastMethod,lastArgs})};
}
test('native owner capability uses actual Registry owner_of and SDK17 Hash.value',async()=>{const f=fixture();const cap=await f.client.nativeClaimCapability('nova');assert.equal(cap.supported,true);if(cap.supported)assert.equal(cap.owner,G);assert.equal(await f.client.claimPolicy('nova'),null);});
test('known old Registrar code reports unsupported without probing nonexistent methods',async()=>{const f=fixture({hash:'ed06b3374ff4342b4a2316fc546505132cd8fd35be6666571cf088710af9bbc6'});assert.deepEqual(await f.client.nativeClaimCapability('nova'),{supported:false,registrar:RAR,reason:'legacy-template'});await assert.rejects(f.client.reserveNames('nova',['admin']),/legacy-template/);assert.equal(f.stats().signed,0);});
test('owner config exact settings, native token and signature are verified',async()=>{const f=fixture(),result=await f.client.configureClaims('nova',settings);assert.equal(result.config.settings.feeToken,TOKEN);assert.equal(f.stats().lastMethod,'configure_claims');assert.equal(f.stats().lastArgs[0].toXDR('base64'),claimSettingsToScVal(settings).toXDR('base64'));});
for(const op of ['reserve','release','assign','pause'] as const)test(`native owner ${op} builds exact ABI`,async()=>{const f=fixture();if(op==='reserve'){await f.client.reserveNames('nova',['Admin','support']);assert.equal(f.stats().lastMethod,'set_reserved');assert.deepEqual(scValToNative(f.stats().lastArgs[0]),[new TextEncoder().encode('admin'),new TextEncoder().encode('support')]);assert.equal(scValToNative(f.stats().lastArgs[1]),true);}if(op==='release'){await f.client.releaseReservations('nova',['admin']);assert.equal(scValToNative(f.stats().lastArgs[1]),false);}if(op==='assign'){await f.client.assignReserved('nova','admin',OTHER);assert.equal(f.stats().lastMethod,'issue_reserved');assert.equal(scValToNative(f.stats().lastArgs[1]),OTHER);}if(op==='pause'){await f.client.pauseClaims('nova');assert.equal(f.stats().lastMethod,'set_claim_enabled');assert.equal(scValToNative(f.stats().lastArgs[0]),false);}assert.equal(f.stats().sent,1);});
test('nonowner and malicious signing wallet never submit native administration',async()=>{for(const options of [{owner:OTHER},{badSignature:true}]){const f=fixture(options);await assert.rejects(f.client.reserveNames('nova',['admin']));assert.equal(f.stats().sent,0);}});
test('invalid reservation batch and approval configurations reject before signing',async()=>{const f=fixture();for(const labels of [[],['admin','ADMIN'],['K'],Array.from({length:24},(_,i)=>'a'+i)])await assert.rejects(f.client.reserveNames('nova',labels));for(const s of [{...settings,feeToken:RES},{...settings,admission:{type:'approval',account:G},approvalAllowance:1n,approvalRateLimit:1n,approvalWindowSecs:60n,approvalTtlSecs:60n},{...settings,approvalAllowance:1n}])await assert.rejects(f.client.configureClaims('nova',s as ClaimSettings));assert.equal(f.stats().signed,0);});

test('confirmed malformed owner result retains original transaction hash',async()=>{const f=fixture({badReturn:true});await assert.rejects(f.client.configureClaims('nova',settings),(e:any)=>e.txHash?.length===64);assert.equal(f.stats().sent,1);});

test('missing simulation payload never masquerades as absent owner configuration',async()=>{const client=new SoranOwner({signer:{publicKey:()=>G,signTransaction:async()=>{throw new Error('must not sign');}}});Object.assign(client,{server:{simulateTransaction:async()=>({_parsed:true,transactionData:new SorobanDataBuilder(),minResourceFee:'0',events:[],latestLedger:1})}});await assert.rejects((client as any).read(RAR,'claim_config',[]),/missing simulation return/);});

// Reproduces the local RPC rent estimate without spending funds or raising defaults.
test('native setup refuses high estimated rent before wallet; explicit cap exposes exact prepared fee',async()=>{
 const blocked=fixture({resourceFee:'1812816220'});
 await assert.rejects(blocked.client.configureClaims('nova',settings),/network fee .* exceeds the configured maximum 50000000 stroops/);
 assert.equal(blocked.stats().signed,0);assert.equal(blocked.stats().sent,0);
 const reviewed=fixture({resourceFee:'1812816220',maxFee:2000000000n});let estimate=0n;
 await reviewed.client.configureClaims('nova',settings,{onPrepared:p=>{estimate=p.feeStroops;}});
 assert.equal(estimate,1812816320n);assert.equal(reviewed.stats().sent,1);
});
