import {instanceProof} from './helpers/native-ledger.mjs';
import assert from 'node:assert/strict';
import test from 'node:test';
import {Account,Address,Keypair,Networks,SorobanDataBuilder,StrKey,TransactionBuilder,hash,scValToNative,xdr} from '@stellar/stellar-sdk';
import {SoranHolder,createClaimIntent,claimIntentToScVal,claimSettingsToScVal,nativeIntentHash,stringifyNativeIntent,parseNativeClaimIntent,encodeMuxedAddress,buildClaimAllowlist,verifyClaimAllowlistProof,claimAllowlistLeaf,signClaimEligibility,type ClaimQuote,type ClaimSettings,type ClaimIntent} from '../src/index.js';
import {authorizedInvocation,type NativeInvocation} from '../src/native-auth.js';
import {hex,namespaceNode,paymentDestinationToScVal,sc,struct} from '../src/native-codec.js';
const kp=Keypair.random(),G=kp.publicKey(),owner=Keypair.random().publicKey(),approver=Keypair.random(),treasury=Keypair.random().publicKey();
const C=(n:number)=>StrKey.encodeContract(new Uint8Array(32).fill(n));const registry=C(1),registrar=C(2),resolver=C(3),token=C(4),node=hex(namespaceNode('nova'));
const nn=new Uint8Array(64);nn.set(namespaceNode('nova'));nn.set(hash(new TextEncoder().encode('alice')),32);const nameNode=hex(hash(nn));
const settings:ClaimSettings={mode:'public',enabled:true,admission:{type:'open'},feeToken:token,feeAmount:10n,feeRecipient:treasury,walletLimit:2n,approvalAllowance:0n,approvalRateLimit:0n,approvalWindowSecs:0n,approvalTtlSecs:0n};
function quote(overrides:Partial<ClaimQuote>={}):ClaimQuote{return{network:hex(hash(new TextEncoder().encode(Networks.TESTNET))),registry,registrar,namespace:node,resolver,label:'alice',node:nameNode,claimant:G,config:{settings,ownerEpoch:1n,policyVersion:2n,grantEpoch:3n},ownerEpoch:1n,policyVersion:2n,available:true,reserved:false,generation:null,expiresAt:null,termSecs:0n,now:1000n,usage:{publicClaims:0n,reservedIssues:0n},approvalUsage:{total:0n,windowUsed:0n,windowEnds:0n},...overrides};}
const bytes=(s:string)=>Uint8Array.from(s.match(/../g)!,v=>parseInt(v,16));
function quoteWire(q:ClaimQuote):unknown{return{network:bytes(q.network),registry:q.registry,registrar:q.registrar,namespace:bytes(q.namespace),resolver:q.resolver,label:new TextEncoder().encode(q.label),node:bytes(q.node),claimant:q.claimant,config:q.config?['Configured',{settings:scValToNative(claimSettingsToScVal(q.config.settings)),owner_epoch:q.config.ownerEpoch,policy_version:q.config.policyVersion,grant_epoch:q.config.grantEpoch}]:['Unconfigured'],owner_epoch:q.ownerEpoch,policy_version:q.policyVersion,available:q.available,reserved:q.reserved,generation:q.generation,expires_at:q.expiresAt,term_secs:q.termSecs,now:q.now,usage:{public_claims:q.usage.publicClaims,reserved_issues:q.usage.reservedIssues},approval_usage:{total:q.approvalUsage.total,window_used:q.approvalUsage.windowUsed,window_ends:q.approvalUsage.windowEnds}};}
function resultWire(intent:ClaimIntent,status='Fresh',ledger=100){return xdr.ScVal.scvVec([sc.symbol(status),struct({operation:xdr.ScVal.scvVec([sc.symbol('Claim')]),intent_hash:sc.bytes(bytes(nativeIntentHash('claim',claimIntentToScVal(intent)))),node:sc.bytes(bytes(nameNode)),holder:sc.address(G),generation:sc.u64(intent.expectedGeneration===null?0n:intent.expectedGeneration+1n),expires_at:sc.u64(intent.termSecs===0n?0n:1000n+intent.termSecs),fee_amount:sc.i128(intent.feeAmount),fee_token:sc.address(token),fee_recipient:intent.feeAmount>0n?sc.address(treasury):xdr.ScVal.scvVoid(),ledger:sc.u32(ledger),timestamp:sc.u64(1000n)})]);}
const destination={address:G,memo:{type:'id',value:'420'}} as const;
const makeIntent=(q=quote(),payment:any=destination)=>createClaimIntent(q,payment,{requestId:'ab'.repeat(32),deadline:1100n});
function fixture(q=quote(),opts:{authMutation?:(auth:xdr.SorobanAuthorizationEntry[])=>void;signerMutation?:boolean;submitError?:boolean;malformedSuccess?:boolean;receiptStatus?:string;receiptLedger?:number;payment?:any}={}){
 let signatures=0,sends=0,record:unknown=null,sentTx:any;const expected=makeIntent(q,opts.payment);
 const holder=new SoranHolder({registryId:registry,passphrase:Networks.TESTNET,signer:{publicKey:()=>G,signTransaction:async(encoded,{networkPassphrase})=>{signatures++;const tx=TransactionBuilder.fromXDR(encoded,networkPassphrase);if(opts.signerMutation){const changed=TransactionBuilder.cloneFrom(tx as any,{networkPassphrase,fee:'999'}).build();changed.sign(kp);return changed.toXDR();}tx.sign(kp);return tx.toXDR();}}});
 const read=async(_id:string,fn:string)=>{if(fn==='registrar_tainted')return false;if(fn==='template_hashes')return[new Uint8Array(32),new Uint8Array(32)];if(fn==='registrar_of')return registrar;if(fn==='native_contracts')return[registrar,resolver];if(fn==='owner_of')return owner;if(fn==='owner_epoch')return 1n;if(fn==='claim_version'||fn==='initialization_version')return 1;if(fn==='anchors')return[registry,bytes(node)];if(fn==='claim_quote')return quoteWire(q);if(fn==='claim_receipt')return record;if(fn==='native_fee_token')return token;throw new Error('unexpected read '+fn);};
 const server={getAccount:async()=>new Account(G,'0'),getLatestLedger:async()=>({sequence:90}),getLedgerEntries:async()=>instanceProof(registrar),getContractInstance:async()=>({executable:{type:'contractExecutableWasm',wasmHash:{value:new Uint8Array(32)}}}),simulateTransaction:async(tx:any)=>{
  const call=tx.operations[0].func.invokeContract,intent=call.args[0],raw=scValToNative(intent);const children:NativeInvocation[]=[];if(raw.fee_amount>0n)children.push({contract:token,method:'transfer',args:[sc.address(G),sc.address(treasury),sc.i128(raw.fee_amount)]});children.push({contract:resolver,method:'initialize_destination',args:[sc.bytes(raw.label),sc.address(G),sc.u64(expected.expectedGeneration===null?0n:expected.expectedGeneration+1n),paymentDestinationToScVal(expected.destination)]});
  const auth=[new xdr.SorobanAuthorizationEntry({credentials:xdr.SorobanCredentials.sorobanCredentialsSourceAccount(),rootInvocation:authorizedInvocation({contract:registrar,method:'claim',args:[intent],children})})];
  if(q.config?.settings.admission.type==='approval')auth.push(new xdr.SorobanAuthorizationEntry({credentials:xdr.SorobanCredentials.sorobanCredentialsAddress(new xdr.SorobanAddressCredentials({address:new Address(approver.publicKey()).toScAddress(),nonce:5n,signatureExpirationLedger:0,signature:xdr.ScVal.scvVoid()})),rootInvocation:authorizedInvocation({contract:registrar,method:'claim',args:[intent]})}));opts.authMutation?.(auth);
  return{_parsed:true,transactionData:new SorobanDataBuilder(),minResourceFee:'0',result:{auth,retval:resultWire(expected)},events:[],latestLedger:90};
 },sendTransaction:async(tx:any)=>{sentTx=tx;sends++;if(opts.submitError)throw new Error('offline after sending');record=scValToNative(resultWire(expected))[1];return{status:'PENDING',hash:hex(tx.hash())};},getTransaction:async()=>({status:'SUCCESS',txHash:hex(sentTx.hash()),envelopeXdr:sentTx.toEnvelope(),ledger:100,returnValue:opts.malformedSuccess?sc.u64(9n):resultWire(expected,opts.receiptStatus??'Fresh',opts.receiptLedger??100)})};
 Object.assign(holder,{read,server,readWithLedger:async(id:string,fn:string,args:xdr.ScVal[])=>({value:await (holder as any).read(id,fn,args),ledger:100})});return{holder,intent:expected,counts:()=>({signatures,sends}),setRecord:(r:unknown)=>record=r};
}
test('native quote decodes exact config enum and context',async()=>{assert.deepEqual(await fixture().holder.claimQuote('ALICE.NOVA'),quote());});
test('native claim signs fee and initializer, then recovers without duplicate effect',async()=>{const f=fixture();let saved='';const result=await f.holder.claim(f.intent,{onPrepared:p=>{saved=p.hash;assert.equal(p.feeStroops,100n);}});assert.equal(result.status,'fresh');assert.equal(result.transaction?.hash,saved);assert.equal(result.receipt.intentHash,nativeIntentHash('claim',claimIntentToScVal(f.intent)));const replay=await f.holder.claim(f.intent);assert.equal(replay.status,'replayed');assert.equal(replay.transaction,null);assert.deepEqual(f.counts(),{signatures:1,sends:1});});
test('recovery does not depend on current paused policy',async()=>{const f=fixture(quote({config:{settings:{...settings,enabled:false},ownerEpoch:7n,policyVersion:9n,grantEpoch:9n}}));f.setRecord(scValToNative(resultWire(f.intent))[1]);assert.equal((await f.holder.claim(f.intent)).status,'replayed');assert.equal(f.counts().signatures,0);});
test('changed intent cannot reuse completed request ID',async()=>{const f=fixture();f.setRecord(scValToNative(resultWire(f.intent))[1]);await assert.rejects(f.holder.claim({...f.intent,destination:{address:G,memo:{type:'none'}}}),/different immutable intent/);assert.equal(f.counts().signatures,0);});
for(const kind of ['auth-extra-child','auth-missing-fee','auth-extra-role','signer-body'] as const)test(`claim rejects ${kind} before broadcast`,async()=>{const f=fixture(quote(),{signerMutation:kind==='signer-body',authMutation:auth=>{if(kind==='auth-extra-child')auth[0].rootInvocation.subInvocations.push(authorizedInvocation({contract:token,method:'transfer',args:[sc.address(G),sc.address(owner),sc.i128(999n)]}));if(kind==='auth-missing-fee')auth[0].rootInvocation.subInvocations.shift();if(kind==='auth-extra-role')auth.push(auth[0]);}});await assert.rejects(f.holder.claim(f.intent));assert.equal(f.counts().sends,0);});
for(const kind of ['unknown-submit','malformed-confirmed-return'] as const)test(`${kind} keeps hash`,async()=>{const f=fixture(quote(),{submitError:kind==='unknown-submit',malformedSuccess:kind==='malformed-confirmed-return'});await assert.rejects(f.holder.claim(f.intent),(e:any)=>e.txHash?.length===64);assert.equal(f.counts().sends,1);});
function approvalQuote(){return quote({config:{...quote().config!,settings:{...settings,admission:{type:'approval',account:approver.publicKey()},approvalAllowance:10n,approvalRateLimit:2n,approvalWindowSecs:3600n,approvalTtlSecs:100n}}});}
test('full claim accepts only separate scoped native approval',async()=>{const q=approvalQuote(),f=fixture(q),built=await f.holder.buildClaim(f.intent);assert(built.eligibilityEntryXdr);const approval=await signClaimEligibility(f.intent,built.eligibilityEntryXdr,{config:q.config!,owner,ownerEpoch:1n,network:q.network,registry,registrar,namespace:node,resolver,networkPassphrase:Networks.TESTNET,latestLedger:90,maxExpirationLedger:150,expirationLedger:120},approver);assert.equal((await f.holder.claim(f.intent,{eligibilityAuthorization:approval})).status,'fresh');assert.equal(f.counts().signatures,1);});
test('missing approval never opens admission or requests a wallet signature',async()=>{const f=fixture(approvalQuote());await assert.rejects(f.holder.claim(f.intent),/expiry|signature/);assert.equal(f.counts().signatures,0);});
test('recovery JSON is lossless and rejects malformed integers',()=>{const i=makeIntent();assert.deepEqual(parseNativeClaimIntent(stringifyNativeIntent(i)),i);assert.throws(()=>parseNativeClaimIntent(stringifyNativeIntent(i).replace('"10"','"01"')));});
test('economic intent changes alter native receipt commitment',()=>{const i=makeIntent(),h=nativeIntentHash('claim',claimIntentToScVal(i));for(const other of [{...i,feeAmount:11n},{...i,feeRecipient:owner},{...i,claimant:owner},{...i,grantEpoch:4n},{...i,policyVersion:3n},{...i,destination:{address:encodeMuxedAddress(G,'420'),memo:{type:'none'}}},{...i,context:{...i.context,requestId:'cd'.repeat(32)}},{...i,context:{...i.context,deadline:1101n}}] as ClaimIntent[])assert.notEqual(nativeIntentHash('claim',claimIntentToScVal(other)),h);});
for(const count of [1,2,3,7])test(`complete allowlist proof bundle ${count} accounts`,()=>{const accounts=Array.from({length:count},()=>Keypair.random().publicKey()),context={network:quote().network,registry,namespace:node,registrar},bundle=buildClaimAllowlist(context,accounts);for(const e of bundle.entries){assert(verifyClaimAllowlistProof(context,e.account,e.proof,bundle.root));assert(!verifyClaimAllowlistProof(context,owner,e.proof,bundle.root));}assert.equal(buildClaimAllowlist(context,[...accounts].reverse()).root,bundle.root);assert.throws(()=>buildClaimAllowlist(context,[accounts[0],accounts[0]]),/duplicate/);assert.notEqual(claimAllowlistLeaf({...context,registrar:resolver},accounts[0]),bundle.entries.find(e=>e.account===accounts[0])!.leaf);});

test('namespace entrypoints reject Unicode before lowercase and without any read',async()=>{const f=fixture();Object.assign(f.holder,{read:async()=>assert.fail('must reject before read')});await assert.rejects(f.holder.nativeClaimCapability('K'),/ASCII/);await assert.rejects(f.holder.claimReceipt('K',G,'ab'.repeat(32)),/ASCII/);});
for(const field of ['registry','registrar','namespace','resolver','ownerEpoch'] as const)test(`approver rejects trusted ${field} substitution`,async()=>{const q=approvalQuote(),f=fixture(q),built=await f.holder.buildClaim(f.intent);const context={config:q.config!,owner,ownerEpoch:1n,network:q.network,registry,registrar,namespace:node,resolver,networkPassphrase:Networks.TESTNET,latestLedger:90,maxExpirationLedger:150,expirationLedger:120};(context as any)[field]=field==='ownerEpoch'?2n:field==='namespace'?'ff'.repeat(32):C(99);await assert.rejects(signClaimEligibility(f.intent,built.eligibilityEntryXdr!,context,approver),/trusted deployment/);});

for(const payment of [{address:G,memo:{type:'none'}},{address:G,memo:{type:'id',value:'18446744073709551615'}},{address:G,memo:{type:'text',value:' customer '}},{address:G,memo:{type:'hash',value:'ab'.repeat(32)}},{address:C(7),memo:{type:'none'}},...['0','9007199254740993','18446744073709551615'].map(id=>({address:encodeMuxedAddress(G,id),memo:{type:'none'}}))])test(`full native claim retains ${payment.address[0]}/${payment.memo.type}/${'value' in payment.memo?payment.memo.value:''}`,async()=>{const f=fixture(quote(),{payment});assert.equal((await f.holder.claim(f.intent)).status,'fresh');assert.deepEqual(f.counts(),{signatures:1,sends:1});});
for(const attack of ['tainted','wrong-code','missing-template'] as const)test(`receipt recovery rejects ${attack} Registrar provenance`,async()=>{const f=fixture();f.setRecord(scValToNative(resultWire(f.intent))[1]);const old=(f.holder as any).read;Object.assign(f.holder,{read:async(id:string,fn:string,args:any)=>{if(fn==='registrar_tainted'&&attack==='tainted')return true;if(fn==='template_hashes'&&attack==='wrong-code')return[new Uint8Array(32).fill(9),new Uint8Array(32)];if(fn==='template_hashes'&&attack==='missing-template')throw new Error('RPC unavailable');return old(id,fn,args);}});await assert.rejects(f.holder.claim(f.intent));assert.equal(f.counts().signatures,0);});

test('expired reissue binds old generation/expiry and initializes only the next generation',async()=>{const f=fixture(quote({generation:7n,expiresAt:999n,termSecs:100n}));const result=await f.holder.claim(f.intent);assert.equal(result.receipt.generation,8n);assert.equal(result.receipt.expiresAt,1100n);assert.equal(f.counts().sends,1);});
for(const status of ['SUCCESS','FAILED'])test(`claim refuses a mismatched terminal ${status} response without another submission`,async()=>{
 const f=fixture(),server=(f.holder as any).server,readReceipt=server.getTransaction;
 server.getTransaction=async()=>({...await readReceipt(),status,txHash:'ff'.repeat(32)});
 await assert.rejects(f.holder.claim(f.intent),(e:any)=>e.kind==='pending'&&e.txHash?.length===64);
 assert.equal(f.counts().sends,1);
 assert.equal((await f.holder.claim(f.intent)).status,'replayed');
 assert.equal(f.counts().sends,1);
});

for (const attack of ['taint-after-inclusion', 'stale-post-inclusion', 'changed-code-after-inclusion'] as const) test(`confirmed claim keeps original hash when ${attack}`, async () => {
 const f=fixture(),target=f.holder as any,read=target.read,server=target.server,entries=server.getLedgerEntries;
 target.read=async(id:string,fn:string,args:xdr.ScVal[])=>fn==='registrar_tainted'&&f.counts().sends>0&&attack==='taint-after-inclusion'?true:read(id,fn,args);
 target.readWithLedger=async(id:string,fn:string,args:xdr.ScVal[])=>({value:await target.read(id,fn,args),ledger:f.counts().sends>0&&attack==='stale-post-inclusion'?99:100});
 server.getLedgerEntries=async()=>f.counts().sends>0&&attack==='changed-code-after-inclusion'?instanceProof(registrar,100,new Uint8Array(32).fill(8)):entries();
 let reviewedHash='';
 await assert.rejects(f.holder.claim(f.intent,{onPrepared:p=>{reviewedHash=p.hash;}}),(error:any)=>error.kind==='pending'&&error.txHash===reviewedHash&&reviewedHash.length===64);
 assert.deepEqual(f.counts(),{signatures:1,sends:1});
});

for (const status of ['Fresh','Replayed']) test(`confirmed ${status} with an older receipt keeps inclusion semantics`, async () => {
 const f=fixture(quote(),{receiptStatus:status,receiptLedger:99});
 if(status==='Fresh') await assert.rejects(f.holder.claim(f.intent),(error:any)=>error.kind==='pending'&&error.txHash?.length===64);
 else {const result=await f.holder.claim(f.intent);assert.equal(result.status,'replayed');assert.equal(result.receipt.ledger,99);assert.equal(result.transaction?.ledger,100);}
 assert.deepEqual(f.counts(),{signatures:1,sends:1});
});
