import assert from 'node:assert/strict';
import test from 'node:test';
import {Account,Keypair,Networks,SorobanDataBuilder,StrKey,TransactionBuilder,hash,scValToNative,xdr} from '@stellar/stellar-sdk';
import {SoranHolder,encodeMuxedAddress,nativeIntentHash,renewIntentToScVal,transferIntentToScVal,type PaymentDestination,type RenewIntent,type TransferIntent} from '../src/index.js';
import {authorizedInvocation} from '../src/native-auth.js';
import {hex,namespaceNode,paymentDestinationToScVal,sc,struct} from '../src/native-codec.js';
const signer=Keypair.random(),G=signer.publicKey(),FROM=Keypair.random().publicKey(),C=(v:number)=>StrKey.encodeContract(new Uint8Array(32).fill(v));const registry=C(1),registrar=C(2),resolver=C(3),token=C(4),namespace=namespaceNode('nova');const node=new Uint8Array(64);node.set(namespace);node.set(hash(new TextEncoder().encode('alice')),32);const nameNode=hash(node);
const context={network:hex(hash(new TextEncoder().encode(Networks.TESTNET))),registry,registrar,namespace:hex(namespace),requestId:'ae'.repeat(32),validAfter:1000n,deadline:1100n};
const matrix:PaymentDestination[]=[{address:G,memo:{type:'none'}},{address:G,memo:{type:'id',value:'18446744073709551615'}},{address:G,memo:{type:'text',value:' customer '}},{address:G,memo:{type:'hash',value:'ab'.repeat(32)}},{address:C(9),memo:{type:'none'}},...["0","9007199254740993","18446744073709551615"].map(id=>({address:encodeMuxedAddress(G,id),memo:{type:'none'}} as PaymentDestination))];
function fixture(intent:TransferIntent|RenewIntent,method:'accept_transfer_with_destination'|'renew_holder',tamper=false){let signed=0,sent=0,sentTx:any;const encoded=method==='renew_holder'?renewIntentToScVal(intent as RenewIntent):transferIntentToScVal(intent as TransferIntent);let stored:unknown=null;const expires=method==='renew_holder'?1100n:2000n;
 const result=xdr.ScVal.scvVec([sc.symbol('Fresh'),struct({operation:xdr.ScVal.scvVec([sc.symbol(method==='renew_holder'?'Renew':'Transfer')]),intent_hash:sc.bytes(Uint8Array.from(nativeIntentHash(method,encoded).match(/../g)!,b=>parseInt(b,16))),node:sc.bytes(nameNode),holder:sc.address(G),generation:sc.u64(method==='renew_holder'?7n:8n),expires_at:sc.u64(expires),fee_amount:sc.i128(0n),fee_token:sc.address(token),fee_recipient:xdr.ScVal.scvVoid(),ledger:sc.u32(99),timestamp:sc.u64(1000n)})]);
 const holder=new SoranHolder({registryId:registry,signer:{publicKey:()=>G,signTransaction:async(raw,{networkPassphrase})=>{signed++;const tx=TransactionBuilder.fromXDR(raw,networkPassphrase);tx.sign(signer);return tx.toXDR();}}});
 Object.assign(holder,{read:async(_id:string,fn:string)=>{if(fn==='registrar_tainted')return false;if(fn==='template_hashes')return[new Uint8Array(32),new Uint8Array(32)];if(fn==='registrar_of')return registrar;if(fn==='native_contracts')return[registrar,resolver];if(fn==='anchors')return[registry,namespace];if(fn==='claim_version')return 1;if(fn==='claim_receipt')return stored;throw new Error('renewal/transfer must not depend on '+fn);},server:{getContractInstance:async()=>({executable:{type:'contractExecutableWasm',wasmHash:{value:new Uint8Array(32)}}}),getAccount:async()=>new Account(G,'0'),simulateTransaction:async()=>{const children=method==='renew_holder'?[]:[{contract:resolver,method:'initialize_destination',args:[sc.bytes(new TextEncoder().encode('alice')),sc.address(G),sc.u64(tamper?9n:8n),paymentDestinationToScVal((intent as TransferIntent).destination)]}];return{_parsed:true,transactionData:new SorobanDataBuilder(),minResourceFee:'0',result:{auth:[new xdr.SorobanAuthorizationEntry({credentials:xdr.SorobanCredentials.sorobanCredentialsSourceAccount(),rootInvocation:authorizedInvocation({contract:registrar,method,args:[encoded],children})})],retval:result},events:[],latestLedger:90};},sendTransaction:async(tx:any)=>{sentTx=tx;sent++;stored=scValToNative(result)[1];return{status:'PENDING',hash:hex(tx.hash())};},getTransaction:async()=>({status:'SUCCESS',txHash:hex(sentTx.hash()),envelopeXdr:sentTx.toEnvelope(),ledger:99,returnValue:result})}});return{holder,counts:()=>({signed,sent})};}
for(const [i,destination]of matrix.entries())test(`atomic recipient transfer preserves complete destination ${i}`,async()=>{const intent:TransferIntent={context,label:'alice',from:FROM,to:G,expectedGeneration:7n,expectedExpiry:2000n,proposalExpires:1200n,destination,resolver};const f=fixture(intent,'accept_transfer_with_destination');const result=await f.holder.acceptNameTransferWithDestination(intent);assert.equal(result.receipt.generation,8n);assert.equal(result.receipt.expiresAt,2000n);assert.equal((await f.holder.acceptNameTransferWithDestination(intent)).status,'replayed');assert.deepEqual(f.counts(),{signed:1,sent:1});});
test('transfer refuses a substituted initializer generation before signing',async()=>{const intent:TransferIntent={context,label:'alice',from:FROM,to:G,expectedGeneration:7n,expectedExpiry:2000n,proposalExpires:1200n,destination:matrix[0],resolver};const f=fixture(intent,'accept_transfer_with_destination',true);await assert.rejects(f.holder.acceptNameTransferWithDestination(intent));assert.deepEqual(f.counts(),{signed:0,sent:0});});
test('holder renewal has no owner, new-claim policy, fee or eligibility dependency',async()=>{const intent:RenewIntent={context,label:'alice',holder:G,expectedGeneration:7n,expectedExpiry:999n,termSecs:100n,minNewExpiry:1100n,maxNewExpiry:1200n};const f=fixture(intent,'renew_holder');const result=await f.holder.renewName(intent);assert.equal(result.receipt.generation,7n);assert.equal(result.receipt.expiresAt,1100n);assert.equal(result.receipt.feeAmount,0n);assert.equal((await f.holder.renewName(intent)).status,'replayed');assert.deepEqual(f.counts(),{signed:1,sent:1});});
