// Generated by sdk/names/sync.mjs; edit sdk/names/names.ts.
/** Canonical resolution grammar. Registration and lifecycle actions still use two labels. */
import { sha256 } from "@noble/hashes/sha2.js";
export type ParsedResolvableName = { name: string; label: string; namespace: string; parent: string | null; parentLabel: string; childLabel: string | null };
const LABEL = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;
export function parseNamespace(input: string): string {
  if (typeof input !== "string" || !/^[A-Za-z0-9-]+$/.test(input)) throw new Error("invalid namespace");
  const value = input.toLowerCase(); if (!LABEL.test(value)) throw new Error("invalid namespace"); return value;
}
export function parseResolvableName(input: string): ParsedResolvableName {
  if (typeof input !== "string" || !/^[A-Za-z0-9.-]+$/.test(input) || input.length > 191) throw new Error("name must contain two or three ASCII labels");
  const name = input.toLowerCase(), parts = name.split(".");
  if ((parts.length !== 2 && parts.length !== 3) || !parts.every(label => LABEL.test(label))) throw new Error("expected label.namespace or child.label.namespace");
  const namespace = parts.at(-1)!, parentLabel = parts.at(-2)!;
  return { name, label: parts.slice(0, -1).join("."), namespace, parent: parts.length === 3 ? `${parentLabel}.${namespace}` : null,
    parentLabel, childLabel: parts.length === 3 ? parts[0] : null };
}
export function resolvableNameNode(input: string): Uint8Array {
  const parts = parseResolvableName(input).name.split(".").reverse();
  let node = new Uint8Array(32);
  for (const part of parts) {
    const joined = new Uint8Array(64); joined.set(node); joined.set(sha256(new TextEncoder().encode(part)), 32); node = new Uint8Array(sha256(joined));
  }
  return node;
}
export type SubnamePolicy = "enabled" | "creation-disabled" | "suspended";
const POLICIES = { enabled: "Enabled", "creation-disabled": "CreationDisabled", suspended: "Suspended" } as const;
export function subnamePolicyToNative(value: SubnamePolicy): string[] {
  if (!Object.hasOwn(POLICIES, value)) throw new Error("invalid subname policy");
  return [POLICIES[value]];
}
export function subnamePolicyFromNative(raw: unknown): SubnamePolicy {
  if (!Array.isArray(raw) || raw.length !== 1 || typeof raw[0] !== "string") throw new Error("invalid subname policy response");
  const policy = (Object.keys(POLICIES) as SubnamePolicy[]).find(key => POLICIES[key] === raw[0]);
  if (!policy) throw new Error("unsupported subname policy"); return policy;
}
export type SubnameRecord = { parentNode: Uint8Array; parentGeneration: bigint; generation: bigint; address: string; active: boolean };
export function exactGeneration(value: unknown): bigint {
  if (typeof value !== "bigint" || value < 0n || value > 18446744073709551615n) throw new Error("generation must be an exact u64 bigint"); return value;
}
/** Address validity is checked by each caller's Stellar SDK, without coercion. */
export function subnameRecordFromNative(raw: unknown, expectedParentNode: Uint8Array): SubnameRecord | null {
  if (raw === null) return null;
  if (!raw || typeof raw !== "object" || Array.isArray(raw) || Object.keys(raw).sort().join(",") !== "active,address,generation,parent_generation,parent_node") throw new Error("invalid subname record fields");
  const r = raw as Record<string, unknown>;
  if (!(r.parent_node instanceof Uint8Array) || r.parent_node.length !== 32 || expectedParentNode.length !== 32 || !r.parent_node.every((byte, i) => byte === expectedParentNode[i]) || typeof r.address !== "string" || typeof r.active !== "boolean") throw new Error("invalid subname record response");
  return { parentNode: new Uint8Array(r.parent_node), parentGeneration: exactGeneration(r.parent_generation), generation: exactGeneration(r.generation), address: r.address, active: r.active };
}
export function subnameLabelsFromNative(raw: unknown, limit: number): string[] {
  if (!Array.isArray(raw) || raw.length > limit) throw new Error("invalid subname labels response");
  const values = raw.map(label => {
    if (!(label instanceof Uint8Array) || label.length < 1 || label.length > 63 || label.some(byte => byte > 127)) throw new Error("invalid subname label bytes");
    const text = new TextDecoder().decode(label); if (!LABEL.test(text)) throw new Error("invalid subname label"); return text;
  });
  if (new Set(values).size !== values.length) throw new Error("duplicate subname label"); return values;
}
export function subnamePageInput(offset = 0, limit = 16): { offset: number; limit: number } {
  if (!Number.isInteger(offset) || offset < 0 || offset > 4294967295 || !Number.isInteger(limit) || limit < 1 || limit > 16 || offset + limit > 4294967295) throw new Error("subname page requires an unsigned offset and a limit from 1 to 16");
  return { offset, limit };
}
