// Generated by sdk/names/sync.mjs; edit sdk/names/subnames-client.ts.
import { hash, nativeToScVal, StrKey, type xdr } from "@stellar/stellar-sdk";
import { parseNamespace, parseResolvableName, resolvableNameNode, subnamePolicyFromNative, subnameRecordFromNative, subnameLabelsFromNative, subnamePageInput, type SubnameRecord } from "./names.js";
export const SUBNAME_REGISTRAR_ERRORS: Record<number, string> = { 53: "SubnameCreationDisabled", 54: "SubnamesSuspended", 55: "SubnameGenerationMismatch", 56: "SubnameIndexUnavailable" };
const account = (value: unknown): value is string => typeof value === "string" && (StrKey.isValidEd25519PublicKey(value) || StrKey.isValidContract(value));
const contract = (value: unknown): value is string => typeof value === "string" && StrKey.isValidContract(value);
export const subnameLabelArg = (value: string) => nativeToScVal(new TextEncoder().encode(value), { type: "bytes" });
export function subnameParent(input: string) { const parsed = parseResolvableName(input); if (parsed.childLabel) throw new Error("parent must be label.namespace"); return parsed; }
export function subnameParts(input: string) { const parsed = parseResolvableName(input); if (!parsed.childLabel) throw new Error("subname must be child.label.namespace"); return parsed; }
export function createSubnameReader(config: { registryId: string; error?: (message: string) => Error; read: (id: string, fn: string, args: xdr.ScVal[]) => Promise<unknown> }) {
  const read = config.read;
  const failure = (message: string) => config.error?.(message) ?? new Error(message);
  async function context(input: string) {
    const namespace = parseNamespace(input);
    if (!contract(config.registryId)) throw failure("invalid Registry");
    const joined = new Uint8Array(64); joined.set(hash(new TextEncoder().encode(namespace)), 32); const node = hash(joined);
    const arg = nativeToScVal(node, { type: "bytes" });
    const [registrar, owner] = await Promise.all([read(config.registryId, "registrar_of", [arg]), read(config.registryId, "owner_of", [arg])]);
    if (!contract(registrar) || !account(owner)) throw failure("namespace has no current Registrar or owner");
    const anchors = await read(registrar, "anchors", []);
    if (!Array.isArray(anchors) || anchors.length !== 2 || anchors[0] !== config.registryId || !(anchors[1] instanceof Uint8Array) || anchors[1].length !== 32 || !node.every((b, i) => b === anchors[1][i])) throw failure("subname Registrar context mismatch");
    if (await read(registrar, "subname_version", []) !== 1) throw failure("subnames unsupported");
    const policy = subnamePolicyFromNative(await read(registrar, "subname_policy", []));
    return { namespace, registrar, owner, policy };
  }
  async function creationContext(input: string) {
    const ctx = await context(input), joined = new Uint8Array(64); joined.set(hash(new TextEncoder().encode(ctx.namespace)), 32);
    const resolver = await read(config.registryId, "resolver_of", [nativeToScVal(hash(joined), { type: "bytes" })]);
    if (!contract(resolver)) throw failure("subnames unsupported: no Resolver");
    const [anchor, authority, version] = await Promise.all([read(resolver, "registry", []), read(resolver, "authority", []), read(resolver, "subname_version", [])]);
    if (anchor !== config.registryId || authority !== ctx.registrar) throw failure("subname Resolver context mismatch");
    if (version !== 1) throw failure("subnames unsupported by Resolver"); return ctx;
  }
  async function recordAt(ctx: Awaited<ReturnType<typeof context>>, parent: string, label: string): Promise<SubnameRecord | null> {
    const record = subnameRecordFromNative(await read(ctx.registrar, "subname_record", [subnameLabelArg(parent), subnameLabelArg(label)]), resolvableNameNode(`${parent}.${ctx.namespace}`));
    if (record && !account(record.address)) throw failure("invalid subname destination"); return record;
  }
  async function record(name: string) { const parsed = subnameParts(name), ctx = await context(parsed.namespace); return recordAt(ctx, parsed.parentLabel, parsed.childLabel!); }
  async function policy(namespace: string) { return (await context(namespace)).policy; }
  async function list(parent: string, options: { offset?: number; limit?: number } = {}) {
    const parsed = subnameParent(parent), { offset, limit } = subnamePageInput(options.offset, options.limit), ctx = await context(parsed.namespace);
    const labels = subnameLabelsFromNative(await read(ctx.registrar, "subname_labels", [subnameLabelArg(parsed.label), nativeToScVal(offset, { type: "u32" }), nativeToScVal(limit, { type: "u32" })]), limit);
    const records = await Promise.all(labels.map(async label => { const record = await recordAt(ctx, parsed.label, label); if (!record) throw failure("subname index references missing record"); return { name: `${label}.${parsed.name}`, ...record }; }));
    return { parent: parsed.name, policy: ctx.policy, records, offset, nextOffset: labels.length === limit ? offset + labels.length : null };
  }
  return { context, creationContext, recordAt, record, policy, list };
}
